default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        name: Conventional pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.0
    hooks:
      - id: stylua
        name: Format Lua code with StyLua
        types:
        - lua
        args:
        - "--config-path=.stylua.toml"
        - "--check"
        additional_dependencies: []

  - repo: local
    hooks:
      - id: luacheck
        name: Lint Lua code with Luacheck
        entry: luacheck
        language: system
        types:
          - lua
        args:
        - "--config"
        - ".luacheckrc"
        - "."
        additional_dependencies: []
