name: Lua Quality Check

on:
  push:
    branches: [main]
  pull_request:

env:
  LUA_VERSION: "5.4"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v12
        with:
            luaVersion: ${{ env.LUA_VERSION }}

      - name: Install Luacheck
        run: luarocks install luacheck

      - name: Run Luacheck
        run: luacheck . --config .luacheckrc

      - name: Install StyLua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip -d /usr/local/bin
          chmod +x /usr/local/bin/stylua

      - name: Run StyLua check
        run: stylua --check --config-path stylua.toml .
