name: Lua Quality Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install and run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
            args: --config .luacheckrc .

      - name: Install and run StyLua check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --config-path stylua.toml .
